# 04.异常处理
- try - except语句  
```python
try:
	#执行代码
except （error_name）:
	#发生异常时执行的代码
```
执行try里面的代码如未发生异常，即忽略except里面的语句；  
否则如果发生异常的错误是error_name,则执行发生异常时的代码；  
如果一个异常没有与任何的 except 匹配，那么这个异常将会传递给上层的 try 中。  
一个except子句可以同时处理多个异常，这些异常将被放在一个括号里成为一个元组，例如:  

```python
except (RuntimeError, TypeError, NameError):
    pass
```
最后一个except子句可以忽略异常的名称，它将被当作通配符使用。  

---

- try - except - else语句  
try-except 语句还有一个可选的 else 子句，如果使用这个子句，那么必须放在所有的 except 子句之后。
else 子句将在 try 子句没有发生任何异常的时候执行。

```python
try:
	#执行代码
except （error_name）:
	#发生异常时执行的代码
else:
	#未发生异常执行的代码
```

---
- try - except - finally 语句  
try-finally 语句无论是否发生异常都将执行最后的代码。

```python
try:
    #检测范围
except Exception[as reason]:
    #出现异常后的处理代码
finally:
    #无论如何都会被执行的代码
```

---
#### 抛出异常  
Python 使用 raise 语句抛出一个指定的异常。  

raise语法格式如下：  

```python
raise [Exception [, args [, traceback]]]
```

Python 使用raise语句抛出一个指定的异常。  

【例子】


```python
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    
# An exception flew by!

```

---
### 猜数字游戏

题目描述:

电脑产生一个零到100之间的随机数字，然后让用户来猜，如果用户猜的数字比这个数字大，提示太大，否则提示太小，当用户正好猜中电脑会提示，"恭喜你猜到了这个数是......"。在用户每次猜测之前程序会输出用户是第几次猜测，如果用户输入的根本不是一个数字，程序会告诉用户"输入无效"。

(尝试使用try catch异常处理结构对输入情况进行处理)

获取随机数采用random模块。

```python
import random
secret = random.randint(0,101)

guess = 101
while guess != secret:

        try:
            guess = int(input("请输入一个0到100的整数:"))
        
            if (guess < 0 and guess > 100):
                print("你输入的数字不符合要求")
            elif (guess < secret):
                print("你输入的数字比谜底要小，再猜一下")
            elif (guess > secret):
                print("你输入的数字比谜底要大，再猜一下")
            else:
                print("恭喜你，猜对了")
                break
        except ValueError:
            print("你输入的格式不符合要求")

```
